[application]

[web.app]

# HTML title tag content
title = "Errday"
short_description = "Errday is your daily task manager."

[bundle]
name = "Errday"
identifier = "ca.mutabie.errday"
publisher = "Mutabie Canada Inc."
icon = ["assets/icon.png"]
category = "Productivity"
copyright = "Â© 2026 Mutabie Canada Inc."
description = "A minimalist task manager using Eisenhower Matrix and Calendar."
# Include the assets folder in the final bundle
resources = ["assets"]

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
